export const ADD_RECORD_STARTED = 'ADD_RECORD_STARTED'
export const ADD_RECORD_SECCEEDED = 'ADD_RECORD_SECCEEDED'
export const ADD_RECORD_FAILED = 'ADD_RECORD_FAILED'

export const EDIT_RECORD_STARTED = 'EDIT_RECORD_STARTED'
export const EDIT_RECORD_SECCEEDED = 'EDIT_RECORD_SECCEEDED'
export const EDIT_RECORD_FAILED = 'EDIT_RECORD_FAILED'

export const REMOVE_RECORD_STARTED = 'REMOVE_RECORD_STARTED'
export const REMOVE_RECORD_SUCCEEDED = 'REMOVE_RECORD_SUCCEEDED'
export const REMOVE_RECORD_FAILED = 'REMOVE_RECORD_FAILED'

export const GET_RECORDS_STARTED = 'GET_RECORDS_STARTED'
export const GET_RECORDS_SUCCEEDED = 'GET_RECORDS_SUCCEEDED'
export const GET_RECORDS_FAILED = 'GET_RECORDS_FAILED'

export const USER_LOGIN_STARTED = 'USER_LOGIN_STARTED'
export const USER_LOGIN_SUCCEEDED = 'USER_LOGIN_SUCCEEDED'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

export const DELETE_USER_STARTED = 'DELETE_USER_STARTED'
export const DELETE_USER_SUCCEEDED = 'DELETE_USER_SUCCEEDED'
export const UDELETE_USER_FAILED = 'UDELETE_USER_FAILED'

export const GET_USER_STARTED = 'GET_USER_STARTED'
export const GET_USER_SUCCEEDED = 'GET_USER_SUCCEEDED'
export const GET_USERS_FAILED = 'GET_USERS_FAILED'

export const GET_ALL_USERS_STARTED = 'GET_ALL_USERS_STARTED'
export const GET_ALL_USERS_SUCCEEDED = 'GET_ALL_USERS_SUCCEEDED'
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED'

export const EDIT_USER_STARTED = 'EDIT_USER_STARTED'
export const EDIT_USER_SUCCEEDED = 'EDIT_USER_SUCCEEDED'
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED'

export const ADD_NEW_USER_STARTED = 'ADD_NEW_USER_STARTED'
export const ADD_NEW_USER_SUCCEEDED = 'ADD_NEW_USER_SUCCEEDED'
export const ADD_NEW_USER_FAILED = 'ADD_NEW_USER_FAILED'

export const SIGN_UP_USER_STARTED = 'SIGN_UP_USER_STARTED'
export const SIGN_UP_USER_SUCCEEDED = 'SIGN_UP_USER_SUCCEEDED'
export const SIGN_UP_USER_FAILED = 'SIGN_UP_USER_FAILED'

export const EDIT_USER_CALORIES_STARTED = 'EDIT_USER_CALORIES_STARTED'
export const EDIT_USER_CALORIES_SUCCEEDED = 'EDIT_USER_CALORIES_SUCCEEDED'
export const EDIT_USER_CALORIES_FAILED = 'EDIT_USER_CALORIES_FAILED'

